#!/usr/bin/env bash

VER="7"
DOCKER_CONT="mlsensor_el${VER}"
SING_NAME="el${VER}_build"

DOCKER_CONF="el${VER}.cont"
SING_CONF="el${VER}.sing"

## BUILD DOCKER CONT
podman build --no-cache --rm --format docker -t ${DOCKER_CONT}:latest -f ${DOCKER_CONF} . || { echo "Fail to build docker image"; exit 1; }

## SAVE DOCKER CONT as oci.archive
[[ -e ${DOCKER_CONT}.tar ]] && rm -rf ${DOCKER_CONT}.tar
podman save --format oci-archive -o ${DOCKER_CONT}.tar localhost/${DOCKER_CONT}:latest || { echo "Saving of container to local tar failed!"; exit 1; }

[[ -e "${SING_NAME}" ]] && rm -f "${SING_NAME}"
singularity build --fakeroot --fix-perms "${SING_NAME}" "${SING_CONF}" || { echo "Singularity build failed!"; exit 1; }
rm -rf ${DOCKER_CONT}.tar

