#!/bin/bash

[[ -z "$1" ]] && echo "The version argument is needed" && exit 1

VER=$1

DIR="MLSensor-"${VER}

rm -rf ${DIR}.tar.gz ${DIR}

mkdir ${DIR}
cp --parents -r bin mlsensord mlsensor.service mlsensor_etc mlsensor_jars mlsensor.spec ${DIR}/

cd ${DIR}
tar czf ../${DIR}.tar.gz *

rm -rf ${DIR}

