#!/bin/bash

[[ -z "$1" ]] && echo "The version argument is needed" && exit 1

VER=$1

DIR="mlsensor-"${VER}

rm -rf ${DIR}.tar.gz ${DIR}

mkdir ${DIR}
cp --parents -r bin mlsensor.service mlsensor_etc mlsensor_jars mlsensor.spec ${DIR}/

tar czf ${DIR}.tar.gz ${DIR}

rm -rf ${DIR}

