#!/bin/bash

[[ -z "$1" ]] && echo "The version argument is needed" && exit 1

VER=$1

DIR="MLSensor-"${VER}

rm -rf ${DIR}.tar.gz ${DIR}

mkdir ${DIR}
cp --parents -r usr/bin/mlsensor_config etc/rc.d/init.d/mlsensord etc/mlsensor/mlsensor_env etc/mlsensor/mlsensor.properties.tmp lib/ ${DIR}/



tar czf ${DIR}.tar.gz ${DIR}

rm -rf ${DIR}